uslugi_kominiarskie/accounts/urls.py
from django.urls import path
from accounts.views import Rejestracja, Logowanie, Wylogowywanie

app_name = 'accounts'

urlpatterns = [
    path('rejestracja/', Rejestracja, name="Rejestracja"),
    path('logowanie/', Logowanie, name="Logowanie"),
    path('wylogowywanie/', Wylogowywanie, name="Wylogowywanie"),
]

uslugi_kominiarskie/uslugi_kominiarskie/urls.py
from django.contrib import admin
from django.urls import path
from kominiarzapp.views import Main, ZamawianieForm, Kominiarze, KominiarzForm, Zamowienia, KominiarzDetail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Main, name="Main"),
    path('zamawianie/', ZamawianieForm, name="Zamawianie"),
    path('kominiarz/', KominiarzForm, name="Kominiarz"),
    path('kominiarze/', Kominiarze.as_view(), name="Kominiarze"),
    path('zamowienia/', Zamowienia.as_view(), name="Zamowienia"),
    path('kominiarz/<int:pk>', KominiarzDetail.as_view(), name="Kominiarz Detale"),
    # listy zamówień
]

uslugi_kominiarskie/accounts/models.py
from django.db import models

# Create your models here.

uslugi_kominiarskie/kominiarzapp/models.py
from django.db import models

# Create your models here.
class Zamowienie(models.Model):
    kominiarz = models.ForeignKey('Kominiarz', on_delete=models.SET_NULL, null=True)
    miasto = models.CharField("Miasto", max_length=20)
    ulica = models.CharField("Ulica", max_length=20)
    numerdomu = models.IntegerField("Numer Domu")
    numermieszkania = models.IntegerField("Numer Mieszkania",null=True, default="", blank=True)
    dzien = models.DateField("Data")

    def __str__(self):
        return str(self.id)

class Kominiarz(models.Model):
    imie = models.CharField("Imię", max_length=20)
    nazwisko = models.CharField("Nazwisko",max_length=20)
    wiek = models.IntegerField("Wiek")
    opis = models.CharField("Opis",max_length=1000,null=True, default="", blank=True)
    zdj = models.CharField("Zdjęcie",max_length=1000,null=True, default="", blank=True)

    def __str__(self):
        return str(self.imie) + " " +str(self.nazwisko)

uslugi_kominiarskie/kominiarzapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Zamowienie, Kominiarz

class Zamawianie(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        numerdomu = cleaned_data.get('numerdomu')
        numermieszkania = cleaned_data.get('numermieszkania')
        
        if not isinstance(numerdomu, int) or not isinstance(numermieszkania, int):
            raise ValidationError("Numer domu i mieszkania musi być liczbą.")
        
        return cleaned_data

    class Meta:
        model = Zamowienie
        fields = ['kominiarz', 'miasto', 'ulica', 'numerdomu', 'numermieszkania', 'dzien']
        widgets = {
        'dzien': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Wybierz date', 'type':'date'}),
    }

class DodawanieKominiarza(forms.ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        wiek = cleaned_data.get('wiek')
        
        if not isinstance(wiek, int):
            raise ValidationError("Wiek musi być liczbą.")
        
        return cleaned_data

    class Meta:
        model = Kominiarz
        fields = ['imie', 'nazwisko', 'wiek', 'opis', 'zdj']

uslugi_kominiarskie/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.views.decorators.csrf import csrf_protect

# Create your views here.
@csrf_protect
def Rejestracja(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("Main")
    else:
        form = UserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/Rejestracja.html', context)

@csrf_protect
def Logowanie(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("Main")
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/Logowanie.html', context)

@csrf_protect
def Wylogowywanie(request):
    if request.method == 'POST':
        logout(request)
        return redirect("Main")

uslugi_kominiarskie/kominiarzapp/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from .models import Kominiarz, Zamowienie
from .forms import Zamawianie, DodawanieKominiarza
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required

def Main(request):
    return render(request, "kominiarzapp/main.html")

class Kominiarze(ListView):
    model = Kominiarz

    def get_queryset(self, *args, **kwargs):
        qs = super(Kominiarze, self).get_queryset(*args, **kwargs)
        return qs

# @login_required(login_url="/accounts/logowanie/")
class Zamowienia(ListView):
    model = Zamowienie
    def get_queryset(self, *args, **kwargs):
        qs = super(Zamowienia, self).get_queryset(*args, **kwargs)
        return qs

def ZamawianieForm(request):
    if request.method == 'POST':
        form = Zamawianie(request.POST)
        if form.is_valid():
            form.save()
        return redirect("Main") 
    else:
        form = Zamawianie()
    context = {
        'form': form
    }
    return render(request, "kominiarzapp/zamawianie.html", context)

@login_required(login_url="/accounts/logowanie/")
def KominiarzForm(request):
    if request.method == 'POST':
        form = DodawanieKominiarza(request.POST)
        if form.is_valid():
            form.save()
        return redirect("Main") 
    else:
        form = DodawanieKominiarza()
    context = {
        'form': form
    }
    return render(request, "kominiarzapp/kominiarz.html", context)

class KominiarzDetail(DetailView):
    model = Kominiarz

uslugi_kominiarskie/kominiarzapp/templates/kominiarzapp/kominiarz.html
{% extends "kominiarzapp/szablon.html" %}
{% load crispy_forms_tags %}
{% block tytul %}Dodawanie Kominiarza{% endblock %}
{% block naglowek%}
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container ">
    <a class="navbar-brand " href="{% url 'Main' %}">
    <div class="mx-auto mt-3 mb-3" >
      <div>
      <img src="/static/img/logo3.png"  style="width: 60%;"></div>
      </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ml-auto ">
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Main' %}">Strona Główna</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Zamawianie' %}">Zamów</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Kominiarze' %}">Kominiarze</a>
        </li>
        <li class="nav-item  ">
          <div class="dropdown ps-4 float-end ">
            <a class="dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Konto
            </a>
          
            <ul class="dropdown-menu mt-2 p-2">
              {% if user.is_authenticated %}
              <li class="d-flex justify-content-center ps-2"><a class="dropdown-item fw-bold" href="{% url 'Kominiarz' %}">Dodaj kominiarza</a></li>
              <li class="d-flex justify-content-center pt-1 ps-1"><a class="dropdown-item" href="{% url 'Zamowienia' %}">Zobacz zamówienia</a></li>
              <li><hr class="dropdown-divider ms-2 me-2"></li>
              <li class="d-flex justify-content-center"><form method="post" action="{% url 'accounts:Wylogowywanie' %}">
                {% csrf_token %}
                <button class="navbar-brand btn ps-4 fs-6 text-center" href="{% url 'accounts:Wylogowywanie' %}">Wyloguj</button>
                </form></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'accounts:Logowanie' %}">Zaloguj się</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:Rejestracja' %}">Zarejestruj się</a></li>
                {% endif %}
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}
{% block formularz %}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 class="text-center">Dodaj nowego kominiarza</h2>
            <h4 class="text-center">
    <form action="" method="post">
        <ul><div class="mx-auto p-5">
        {% csrf_token %}
        {{form|crispy}}   </div>
        </ul>
        <div class="row justify-content-center">      
        <input class="btn btn-danger" type="submit" value="Dodaj">
        </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

uslugi_kominiarskie/kominiarzapp/templates/kominiarzapp/kominiarz_detail.html
{% extends "kominiarzapp/szablon.html" %}
{% block naglowek%}
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container ">
      <a class="navbar-brand " href="{% url 'Main' %}">
      <div class="mx-auto mt-3 mb-3" >
        <div>
        <img src="/static/img/logo3.png"  style="width: 60%;"></div>
        </div>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav ml-auto ">
          <li class="nav-item">
            <a class="navbar-brand ps-4" href="{% url 'Main' %}">Strona Główna</a>
          </li>
          <li class="nav-item">
            <a class="navbar-brand ps-4" href="{% url 'Zamawianie' %}">Zamów</a>
          </li>
          <li class="nav-item">
            <a class="navbar-brand ps-4" href="{% url 'Kominiarze' %}">Kominiarze</a>
          </li>
          <li class="nav-item  ">
            <div class="dropdown ps-4 float-end ">
              <a class="dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Konto
              </a>
            
              <ul class="dropdown-menu mt-2 p-2">
                {% if user.is_authenticated %}
                <li class="d-flex justify-content-center ps-2"><a class="dropdown-item" href="{% url 'Kominiarz' %}">Dodaj kominiarza</a></li>
                <li class="d-flex justify-content-center pt-1 ps-1"><a class="dropdown-item" href="{% url 'Zamowienia' %}">Zobacz zamówienia</a></li>
                <li><hr class="dropdown-divider ms-2 me-2"></li>
                <li class="d-flex justify-content-center"><form method="post" action="{% url 'accounts:Wylogowywanie' %}">
                  {% csrf_token %}
                  <button class="navbar-brand btn ps-4 fs-6 text-center" href="{% url 'accounts:Wylogowywanie' %}">Wyloguj</button>
                  </form></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{% url 'accounts:Logowanie' %}">Zaloguj się</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:Rejestracja' %}">Zarejestruj się</a></li>
                  {% endif %}
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block formularz %}
<div class="row justify-content-center">
<h1 class="row justify-content-center mt-3">Detale Kominiarza</h1>
    <div class="card mb-3 mt-4 border border-3 border-black" style="width: 50%; margin-left: 25%; margin-right: 25%;">
      <img src={{object.zdj}} class="card-img-top pt-3" alt="...">
      <div class="card-body">
        <h5 class="card-title">ID: {{object.id}}</h5>
        <p class="card-text">Imie: {{object.imie}}</p>
        <p class="card-text">Nazwisko: {{object.nazwisko}}</p>
        <p class="card-text">Wiek: {{object.wiek}}</p>
        <p class="card-text">Opis: {{object.opis}}</p>
      </div>
    </div>
</div>
{% endblock %}

uslugi_kominiarskie/kominiarzapp/templates/kominiarzapp/kominiarz_list.html
{% extends "kominiarzapp/szablon.html" %}
{% block naglowek%}
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container ">
      <a class="navbar-brand " href="{% url 'Main' %}">
      <div class="mx-auto mt-3 mb-3" >
        <div>
        <img src="/static/img/logo3.png"  style="width: 60%;"></div>
        </div>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav ml-auto ">
          <li class="nav-item">
            <a class="navbar-brand ps-4" href="{% url 'Main' %}">Strona Główna</a>
          </li>
          <li class="nav-item">
            <a class="navbar-brand ps-4" href="{% url 'Zamawianie' %}">Zamów</a>
          </li>
          <li class="nav-item">
            <a class="navbar-brand ps-4 fw-bold" href="{% url 'Kominiarze' %}">Kominiarze</a>
          </li>
          <li class="nav-item  ">
            <div class="dropdown ps-4 float-end ">
              <a class="dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Konto
              </a>
            
              <ul class="dropdown-menu mt-2 p-2">
                {% if user.is_authenticated %}
                <li class="d-flex justify-content-center ps-2"><a class="dropdown-item" href="{% url 'Kominiarz' %}">Dodaj kominiarza</a></li>
                <li class="d-flex justify-content-center pt-1 ps-1"><a class="dropdown-item" href="{% url 'Zamowienia' %}">Zobacz zamówienia</a></li>
                <li><hr class="dropdown-divider ms-2 me-2"></li>
                <li class="d-flex justify-content-center"><form method="post" action="{% url 'accounts:Wylogowywanie' %}">
                  {% csrf_token %}
                  <button class="navbar-brand btn ps-4 fs-6 text-center" href="{% url 'accounts:Wylogowywanie' %}">Wyloguj</button>
                  </form></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{% url 'accounts:Logowanie' %}">Zaloguj się</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:Rejestracja' %}">Zarejestruj się</a></li>
                  {% endif %}
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block formularz %}
<div class="row justify-content-center">
<h1 class="row justify-content-center mt-3">Wybierz swojego Kominiarza</h1>
<form action="" method="post">
    {% for object in object_list %}
    <div class="card mb-3 mt-4 border border-3 border-black" style="width: 50%; margin-left: 25%; margin-right: 25%;">
        <img src={{object.zdj}} class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{object.imie}} {{object.nazwisko}}</h5>
          <p class="card-text">{{object.opis|safe}}...</p>
          <p class="card-text"><small class="text-body-secondary">Wiek: {{object.wiek}}<a class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" style="float: right;" href="../kominiarz/{{object.id}}">Zobacz więcej</a></small></p>
        </div>
      </div>
      
    {% endfor %}
</form>
</div>
{% endblock %}

uslugi_kominiarskie/kominiarzapp/templates/kominiarzapp/main.html
{% extends "kominiarzapp/szablon.html" %}
{% block tytul %}Strona Glówna{% endblock %}
{% block tresc %}{% endblock %}
<!-- /static/img/glowna1.jpg-->
{% block naglowek%}


<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container ">
    <a class="navbar-brand " href="{% url 'Main' %}">
    <div class="mx-auto mt-3 mb-3" >
      <div>
      <img src="/static/img/logo3.png"  style="width: 60%;"></div>
      </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ml-auto ">
        <li class="nav-item">
          <a class="navbar-brand ps-4 fw-bold" href="{% url 'Main' %}">Strona Główna</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Zamawianie' %}">Zamów</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Kominiarze' %}">Kominiarze</a>
        </li>
        <li class="nav-item  ">
          <div class="dropdown ps-4 float-end ">
            <a class="dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Konto
            </a>
          
            <ul class="dropdown-menu mt-2 p-2">
              {% if user.is_authenticated %}
              <li class="d-flex justify-content-center ps-2"><a class="dropdown-item " href="{% url 'Kominiarz' %}">Dodaj kominiarza</a></li>
              <li class="d-flex justify-content-center pt-1 ps-1"><a class="dropdown-item" href="{% url 'Zamowienia' %}">Zobacz zamówienia</a></li>
              <li><hr class="dropdown-divider ms-2 me-2"></li>
              <li class="d-flex justify-content-center"><form method="post" action="{% url 'accounts:Wylogowywanie' %}">
                {% csrf_token %}
                <button class="navbar-brand btn ps-4 fs-6 text-center" href="{% url 'accounts:Wylogowywanie' %}">Wyloguj</button>
                </form></li>
                {% else %}
                <li><a class="dropdown-item " href="{% url 'accounts:Logowanie' %}">Zaloguj się</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:Rejestracja' %}">Zarejestruj się</a></li>
                {% endif %}
            </ul>
          </div>
        </li>

      </ul>
    </div>
  </div>
</nav>








{% endblock %}
  {% block zdjecia %}
  <div id="carouselExampleCaptions" class="carousel slide m-2" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="/static/img/glowna1.jpg" class="d-block w-100 img-thumbnail" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>Systemy kominowe i nasady kominowe Trójmiasto</h1>
          <p class="fs-4">30 lat gwarancji na systemy kominowe !!</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="/static/img/glowna2.jpg" class="d-block w-100 img-thumbnail" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>Nasi kominiarze</h1>
          <p class="fs-4">Tak zmontują komin że to baranie jaja</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="/static/img/glowna5.jpg" class="d-block w-100 img-thumbnail" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>Takie o kominy montujemy</h1>
          <p class="fs-4">Że aż sąsiad będzie zazdrościł</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div><br><br><br><br>
  </div>

  <div class="container text-center ">
    <div class="row">
      <div class="col">
        <img src="/static/img/glowna4.jpg" class="pb-3 rounded" style="width: 75%; margin-left: -40%;">
      </div>
      <div class="col">
        <p class="fs-3 text-danger ">Wyspecjalizowany zespół i pełen wachlarz usług</p><br>
        <p class="fs-4">Zapraszamy do skorzystania z szerokiej gamy usług kominiarskich w Trójmieście i okolicach! Jesteśmy doświadczoną firmą specjalizującą się w kompleksowej obsłudze różnorodnych systemów kominowych i wentylacyjnych. Nasz zespół składa się z wykwalifikowanych kominiarzy, posiadających bogatą wiedzę teoretyczną oraz praktyczne umiejętności zdobyte przez lata pracy w branży.</p><br>
        <p class="fs-4">Oferujemy pełen zakres usług, w tym: montaż kominów, frezowanie kominów, uszczelnianie przewodów kominowych oraz montaż kominów izolowanych. Nasza firma kładzie nacisk na najwyższą jakość usług i całkowite zadowolenie klienta.</p><br>
        <p class="fs-4">Działamy sprawnie i profesjonalnie na terenie województwa pomorskiego, dostosowując się do indywidualnych potrzeb i wymagań każdego zlecenia.</p>
        <p class="fs-4 fw-bold">Zachęcamy do współpracy!</p>
        <a href="{% url 'Zamawianie' %}"><button class="btn btn-danger" type="button">Zamów usługę już teraz</button></a>
      </div>
    </div>



  
  {% endblock %}

uslugi_kominiarskie/kominiarzapp/templates/kominiarzapp/zamawianie.html
{% extends "kominiarzapp/szablon.html" %}
{% load crispy_forms_tags %}
{% block tytul %}Zamawianie{% endblock %}
{% block naglowek%}
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container ">
    <a class="navbar-brand " href="{% url 'Main' %}">
    <div class="mx-auto mt-3 mb-3" >
      <div>
      <img src="/static/img/logo3.png"  style="width: 60%;"></div>
      </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ml-auto ">
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Main' %}">Strona Główna</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand ps-4 fw-bold" href="{% url 'Zamawianie' %}">Zamów</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand ps-4" href="{% url 'Kominiarze' %}">Kominiarze</a>
        </li>
        <li class="nav-item  ">
          <div class="dropdown ps-4 float-end ">
            <a class="dropdown-toggle navbar-brand" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Konto
            </a>
          
            <ul class="dropdown-menu mt-2 p-2">
              {% if user.is_authenticated %}
              <li class="d-flex justify-content-center ps-2"><a class="dropdown-item" href="{% url 'Kominiarz' %}">Dodaj kominiarza</a></li>
              <li class="d-flex justify-content-center pt-1 ps-1"><a class="dropdown-item" href="{% url 'Zamowienia' %}">Zobacz zamówienia</a></li>
              <li><hr class="dropdown-divider ms-2 me-2"></li>
              <li class="d-flex justify-content-center"><form method="post" action="{% url 'accounts:Wylogowywanie' %}">
                {% csrf_token %}
                <button class="navbar-brand btn ps-4 fs-6 text-center" href="{% url 'accounts:Wylogowywanie' %}">Wyloguj</button>
                </form></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'accounts:Logowanie' %}">Zaloguj się</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:Rejestracja' %}">Zarejestruj się</a></li>
                {% endif %}
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}
{% block formularz %}
<div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 class="text-center">Zamów usługe kominiarską</h2>
            <h4 class="text-center">
                
              
    <form action="" method="post">
        
        <ul><div class="mx-auto p-5">
           
         
        {% csrf_token %}
        {{form|crispy}}   </div>
        </ul>
        <div class="row justify-content-center">      
        <input class="btn btn-danger" type="submit" value="Dodaj">
        </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}